config/routes.rb
      get :home_settings
      get :pagination
      get :settings
      get :get_stats
      get :registration_form
      get :edit_tag
      post :update_home_settings
      post :restart_server
      post :restart_delayed_job
      post :update_admins
      post :update_rebrand
      post :test_email_configuration
      post :update_settings
      post :update_features_enabled
      post :update_pagination
      post :delete_tag
      post :edit_tag
      post :update_imprint_setting
      post :clear_failed_jobs
    end
    concerns :has_dashboard, controller: :stats
  end

  resource :home do
    member do
      get :index
      get :feedback
      get :funding
      post :send_feedback
      get :imprint
      get :terms
      get :privacy
      get :about
      get :create_or_join_project
    end
  end

  get 'funding' => 'homes#funding', as: :funding
  get 'index.html' => 'homes#index'
  get 'index' => 'homes#index'

  resource :favourites do
    collection do
      post :add
    end
    member do
      delete :delete
    end
  end

  resources :help, controller: 'help_documents', as: :help_documents do
    resources :attachments, controller: 'help_attachments', as: :help_attachments, only: [:create, :destroy] do
      member do
        get :download
      end
    end
    resources :images, controller: 'help_images', as: :help_images, only: [:create, :destroy] do
      member do
        get :view
      end
    end
  end
  resources :help_attachments, only: [:create, :destroy] do
    member do
      get :download
    end
  end
  resources :help_images, only: [:create, :destroy] do
    member do
      get :view
    end
  end

  resources :avatars
  resources :attachments
  resources :subscriptions
  resources :measured_items
  resources :saved_searches
  resources :uuids
  resources :compounds do
    collection do
      post :search_in_sabiork
    end
  end

  # resources :project_folders

  ### USERS AND SESSIONS ###

  resources :users do
    collection do
      get :activation_required
      get :forgot_password
      get :reset_password
      post :forgot_password
      post :hide_guide_box
      post :impersonate
      post :cancel_registration
      post :bulk_destroy
    end
    member do
      put :set_openid
      post :resend_activation_email
    end
    resources :oauth_sessions, only: [:index, :destroy]
    resources :identities, only: [:index, :destroy]
    resources :api_tokens, only: [:index, :create, :destroy]
  end

  resource :session do
    collection do
      get :index
      get :show
      get :auto_openid
    end
    member do
      get :show
    end
  end

  ### YELLOW PAGES ###

  resources :people, concerns: [:publishable] do
    collection do
      get :typeahead
      get :register
      get :current
      get :is_this_you
      get :get_work_group
      post :userless_project_selected_ajax
      post :items_for_result
      post :bulk_destroy
    end
    member do
      get :batch_publishing_preview
      get :requested_approval_assets
      post :gatekeeper_decide
      get :gatekeeper_decision_result
      get :waiting_approval_assets
      get :select
      get :items
    end
    resources :projects, :institutions, :assays, :studies, :investigations, :models, :sops, :workflows, :nodes, :data_files, :presentations, :publications, :documents, :events, :samples, :specimens, :strains, :collections, only: [:index]
    resources :avatars do
      member do
        post :select
      end
    end
  end

  resources :projects do
    collection do
      get :request_institutions
      get :manage
      post :items_for_result
      get :guided_join
      get :guided_create
      post :request_join
      post :request_create
    end
    member do
      get :asset_report
      get :admin_members
      get :admin_member_roles
      get :storage_report
      post :update_members
      post :request_membership
      get :overview
      get :administer_join_request
      post :respond_join_request
    end
    resources :people, :institutions, :assays, :studies, :investigations, :models, :sops, :workflows, :nodes, :data_files, :presentations,
              :publications, :events, :samples, :specimens, :strains, :search, :organisms, :human_diseases, :documents, :collections, only: [:index]

    resources :openbis_endpoints do
      collection do
        get :test_endpoint
        get :fetch_spaces
        get :browse
      end
    end
    resources :avatars do
      member do
        post :select
      end
    end
    resources :folders do
      collection do
        post :nuke
      end
      member do
        post :remove_asset
        get :display_contents
        post :move_asset_to
        post :create_folder
        post :set_project_folder_title
        post :set_project_folder_description
      end
    end
    concerns :has_dashboard, controller: :project_stats
  end

  resources :openbis_endpoints do
    get :test_endpoint, on: :member
    get :fetch_spaces, on: :member
    get :refresh, on: :member
    get :reset_fatals, on: :member
    resources :openbis_experiments do
      get :refresh, on: :member
      post :register, on: :member
      post :batch_register, on: :collection
    end
    resources :openbis_zamples do
      get :refresh, on: :member
      post :register, on: :member
      post :batch_register, on: :collection
    end
    resources :openbis_datasets do
      get :refresh, on: :member
      post :register, on: :member
      get :show_dataset_files, on: :member
      post :batch_register, on: :collection
    end
  end

  resources :institutions do
    collection do
      post :items_for_result
      get  :typeahead
    end
    resources :people, :projects, :specimens, only: [:index]
    resources :avatars do
      member do
        post :select
      end
    end
  end

  ### ISA ###

  resources :investigations, concerns: [:publishable, :has_snapshots, :isa] do
    resources :people, :projects, :assays, :studies, :models, :sops, :workflows, :nodes, :data_files, :publications, :documents, only: [:index]
    member do
      get :export_isatab_json
    end
  end

  resources :studies, concerns: [:publishable, :has_snapshots, :isa] do
    collection do
      post :investigation_selected_ajax
    end
    resources :people, :projects, :assays, :investigations, :models, :sops, :workflows, :nodes, :data_files, :publications, :documents, only: [:index]
  end

  resources :assays, concerns: [:publishable, :has_snapshots, :isa] do
    resources :nels, only: [:index] do
      collection do
        get :projects
        get :datasets
        get :dataset
        post :register
      end
    end
    resources :people, :projects, :investigations, :samples, :studies, :models, :sops, :workflows, :nodes, :data_files, :publications, :documents, :strains, :organisms, :human_diseases, only: [:index]
  end

  # to be removed as STI does not work in too many places
  # resources :openbis_assays, controller: 'assays', type: 'OpenbisAssay'

  ### ASSAY AND TECHNOLOGY TYPES ###

  resources :suggested_assay_types
  resources :suggested_modelling_analysis_types, path: :suggested_assay_types, controller: :suggested_assay_types
  resources :suggested_technology_types

  ### ASSETS ###

  resources :data_files, concerns: [:has_content_blobs, :has_versions, :has_doi, :publishable, :asset] do
    collection do
      get :filter
      post :upload_for_tool
      post :upload_from_email
      get :provide_metadata
      post :create_content_blob
      post :rightfield_extraction_ajax
      post :create_metadata
    end
    member do
      get :plot
      get :explore
      get :samples_table
      get :select_sample_type
      get :confirm_extraction
      get :extraction_status
      post :extract_samples
      delete :cancel_extraction
      get :destroy_samples_confirm
      post :retrieve_nels_sample_metadata
      get :retrieve_nels_sample_metadata
    end
    resources :studied_factors do
      collection do
        post :create_from_existing
      end
    end
    resources :people, :projects, :investigations, :assays, :samples, :studies, :publications, :events, :collections, only: [:index]
  end

  resources :presentations, concerns: [:has_content_blobs, :publishable, :has_versions, :asset] do
    resources :people, :projects, :publications, :events, :collections, only: [:index]
  end

  resources :models, concerns: [:has_content_blobs, :publishable, :has_doi, :has_versions, :asset] do
    member do
      get :compare_versions
      post :compare_versions
      get :visualise
      post :submit_to_sycamore
      post :export_as_xgmml
      post :execute
      get :simulate
      post :simulate
    end
    resources :model_images do
      collection do
        post :new
      end
      member do
        post :select
      end
    end
    resources :people, :projects, :investigations, :assays, :studies, :publications, :events, :collections, only: [:index]
  end

  resources :sops, concerns: [:has_content_blobs, :publishable, :has_doi, :has_versions, :asset] do
    resources :experimental_conditions do
      collection do
        post :create_from_existing
      end
    end
    resources :people, :projects, :investigations, :assays, :samples, :studies, :publications, :events, :workflows, :collections, only: [:index]
  end

  resources :workflows, concerns: [:has_content_blobs, :publishable, :has_doi, :has_versions, :asset] do
    collection do
      post :create_content_blob
      post :create_ro_crate
      get :provide_metadata
      post :metadata_extraction_ajax
      post :create_metadata
    end
    member do
      get :diagram
      get :ro_crate
    end
    resources :people, :projects, :investigations, :assays, :samples, :studies, :publications, :events, :sops, :collections, only: [:index]
  end

  resources :nodes, concerns: [:has_content_blobs, :publishable, :has_doi, :has_versions, :asset] do

app/helpers/samples_helper.rb
module SamplesHelper
  def sample_form_field_for_attribute(attribute)
    base_type = attribute.sample_attribute_type.base_type
    clz = "sample_attribute_#{base_type.downcase}"
    attribute_method_name = attribute.method_name
    placeholder = "e.g. #{attribute.sample_attribute_type.placeholder}" unless attribute.sample_attribute_type.placeholder.blank?

    case base_type
    when Seek::Samples::BaseType::TEXT
      text_area :sample, attribute_method_name, class: "form-control #{clz}"
    when Seek::Samples::BaseType::DATE_TIME
      content_tag :div, style:'position:relative' do
        text_field :sample, attribute_method_name, data: { calendar: 'mixed' }, class: "calendar form-control #{clz}", placeholder: placeholder
      end
    when Seek::Samples::BaseType::DATE
      content_tag :div, style:'position:relative' do
        text_field :sample, attribute_method_name, data: { calendar: true }, class: "calendar form-control #{clz}", placeholder: placeholder
      end
    when Seek::Samples::BaseType::BOOLEAN
      check_box :sample, attribute_method_name, class: "#{clz}"
    when Seek::Samples::BaseType::SEEK_STRAIN
      selected_id = @sample ? @sample.send(attribute_method_name).try(:[], 'id') : nil
      options = option_groups_from_collection_for_select(Organism.all, :strains, :title, :id, :title, selected_id)
      select(:sample, attribute_method_name, options, { include_blank: !attribute.required? }, class: "form-control #{clz}")
    when Seek::Samples::BaseType::CV
      terms = attribute.sample_controlled_vocab.sample_controlled_vocab_terms
      collection_select :sample, attribute_method_name, terms, :label, :label,
                        { include_blank: !attribute.required? }, class: "form-control #{clz}"
    when Seek::Samples::BaseType::SEEK_SAMPLE
      terms = attribute.linked_sample_type.samples.authorized_for('view').to_a
      collection_select :sample, attribute_method_name, terms, :id, :title,
                        { include_blank: !attribute.required? }, class: "form-control #{clz}"
    else
      text_field :sample, attribute_method_name, class: "form-control #{clz}", placeholder: placeholder
    end
  end

  def authorised_samples(projects = nil)
    authorised_assets(Sample, projects)
  end

  def sample_attribute_title_and_unit(attribute)
    title = attribute.title
    if (unit = attribute.unit) && !unit.dimensionless?
      title += " ( #{unit} )"
    end
    title
  end

  def display_attribute(sample, attribute, options = {})
    value = sample.get_attribute_value(attribute)
    if value.blank?
      text_or_not_specified(value)
    else
      case attribute.sample_attribute_type.base_type
      when Seek::Samples::BaseType::DATE
        Date.parse(value).strftime('%e %B %Y')
      when Seek::Samples::BaseType::DATE_TIME
        DateTime.parse(value).strftime('%e %B %Y %H:%M:%S')
      when Seek::Samples::BaseType::SEEK_STRAIN
        seek_strain_attribute_display(value)
      when Seek::Samples::BaseType::SEEK_SAMPLE
        seek_sample_attribute_display(value)
      else
        default_attribute_display(attribute, options, sample, value)
      end
    end
  end

  def seek_sample_attribute_display(value)
    sample = Sample.find_by_id(value['id'])
    if sample
      if sample.can_view?
        link_to sample.title, sample
      else
        content_tag :span, 'Hidden', class: 'none_text'
      end
    else
      content_tag :span, value['title'], class: 'none_text'
    end
  end

  def default_attribute_display(attribute, options, sample, value)
    resolution = attribute.resolve (value)
    if (resolution != nil)
      link_to(value, resolution, target: :_blank)
    else if options[:link] && attribute.is_title
        link_to(value, sample)
      else
      
        text_or_not_specified(value, auto_link: options[:link])
      end
    end
  end

  def seek_strain_attribute_display(value)
    if value && value['id']
      if value['title']
        link_to(value['title'], strain_path(value['id']))
      else
        content_tag(:span, value['id'], class: 'none_text')
      end
    else
      content_tag(:span, 'Not specified', class: 'none_text')
    end
  end

  # link for the sample type for the provided sample. Handles a referring_sample_id if required
  def sample_type_link(sample, user=User.current_user)
    if (sample.sample_type.can_view?(user))
      link_to sample.sample_type.title,sample.sample_type
    else
      link_to sample.sample_type.title,sample_type_path(sample.sample_type, referring_sample_id:sample.id)
    end
  end

  def sample_type_list_item_attribute(attribute, sample)
    value = sample_type_link(sample)
    html = content_tag(:p,class:'list_item_attribute') do
      content_tag(:b) do
        "#{attribute}: "
      end + value
    end
    html.html_safe
  end

end

app/views/samples/_associate_sample.html.erb
<%
  return unless Seek::Config.samples_enabled
  resource_text ||= text_for_resource(resource)

  assay_assets = resource.assay_assets.select { |aa| aa.asset_type == 'Sample' }

  samples = Sample.joins(:projects).where(projects: { id: current_user.person.projects.map(&:id) }).limit(100).order('updated_at DESC')
  authorized_samples = samples.authorized_for('view')

  data_files = DataFile.with_extracted_samples.authorized_for('view').select { |d| d.extracted_samples.any? }.first(20)

  field_name = "#{resource.class.name.underscore}[samples_attributes]"
  collapse_panel = assay_assets.empty?
  associated_samples_json = associations_json_from_assay_assets(assay_assets, fieldName: field_name)
-%>

<%= folding_panel("Samples", collapse_panel, :body_options => {:id => 'associate_sample_fold_content'},
                  :help_text => "Here you associate Samples in SEEK to this #{resource_text}.") do %>

    <p>The following Samples are involved in this <%= resource_text -%>:</p>

    <%= associations_list_group('sample_to_list', 'direction.value', associated_samples_json) do %>
        <div class="row">
          <div class="col-md-4">
            <h3>Incoming</h3>
            <%= associations_list('incoming-sample-list', 'associations/sample', '',
                                  empty_text: 'No incoming samples',
                                  'data-field-name' => field_name,
                                  'data-multilist-group-value' => AssayAsset::Direction::INCOMING) %>
          </div>
          <div class="col-md-4">
            <h3>Outgoing</h3>
            <%= associations_list('outgoing-sample-list', 'associations/sample', '',
                                  empty_text: 'No outgoing samples',
                                  'data-field-name' => field_name,
                                  'data-multilist-group-value' => AssayAsset::Direction::OUTGOING) %>
          </div>
          <div class="col-md-4">
            <h3>No direction</h3>
            <%= associations_list('other-sample-list', 'associations/sample', '',
                                  empty_text: 'No other samples',
                                  'data-field-name' => field_name,
                                  'data-multilist-group-value' => AssayAsset::Direction::NODIRECTION) %>
          </div>
        </div>
    <% end %>

    <hr/>

    <%= association_selector('sample_to_list', 'Add individual samples', 'Select samples') do %>
        <label>Select samples</label>
        <%= filterable_association_select(filter_samples_path(:assay_id => resource.id), :multiple => true) do %>
            <%= render :partial => 'samples/association_preview',
                       :collection => authorized_samples,
                       :locals => { :existing => resource.samples }
            %>
        <% end %>

        <hr/>

        <div class="form-group">
          <label>Select sample direction</label>
          <%= select_tag(:direction, direction_options, :class => 'form-control', :autocomplete => 'off',
                         'data-role' => 'seek-association-common-field') %>
        </div>
    <% end %>

    <%= button_link_to('Add samples from data file', 'add', '#', 'data-toggle' => 'modal', 'data-target' => "#AddSamplesFromDataFileModal") %>
    <%= modal(id: 'AddSamplesFromDataFileModal', size: 'xl', 'data-role' => 'seek-wizard') do %>
        <%= modal_header('Add samples from data file') %>
        <%= modal_body do %>
            <div data-role="seek-wizard-nav"></div>
            <div data-role="seek-wizard-step" data-step-name="Select data file" id="samples-select-data-file">
              <label>Select data file</label>
              <%= filterable_association_select(filter_data_files_path(with_samples: true)) do %>
                  <%= render :partial => 'data_files/association_preview',
                             :collection => data_files,
                             :locals => { :existing => resource.samples }
                  %>
              <% end %>
            </div>
            <div data-role="seek-wizard-step" data-step-name="Select samples">
              <label>Select samples</label>
              <div id="data-file-samples-table">
                <%= image('spinner') %>
              </div>
            </div>
            <div data-role="seek-wizard-step" data-step-name="Select sample direction">
              <div class="form-group">
                <label>Select sample direction</label>
                <%= select_tag(:direction, direction_options, :class => 'form-control', :autocomplete => 'off',
                               'data-role' => 'seek-association-common-field') %>
              </div>
            </div>
        <% end %>
        <%= modal_footer do %>
            <a data-role="seek-wizard-next-btn" href="#" class="pull-right btn btn-default">Next</a>
            <a data-role="seek-wizard-prev-btn" href="#" class="pull-left btn btn-default">Previous</a>
            <%= confirm_association_button('Add samples', id: 'add-batch-sample-btn', style: 'display: none',
                                           class: 'btn btn-primary pull-right', 'data-dismiss' => 'modal') %>
        <% end %>
    <% end %>
    <%= button_link_to('Clear all samples', 'destroy', '#', id: 'clear-all-samples-btn') %>
<% end %>

<script>
  var wizard;
  $j(document).ready(function () {
    // Reset the "Add individual samples" modal after it is closed
    $j('#modalAddIndividualSamples').on('hidden.bs.modal', function () {
      $j('[data-role="seek-association-filter-group"]', $j(this)).data('filterGroup').reset();
      $j('select', $j(this)).val('0');
    });

    var samplesList = $j('#sample_to_list').data('associationList');
    var batchSamplesForm = new Associations.Form(samplesList, $j('#AddSamplesFromDataFileModal'));
    $j('#AddSamplesFromDataFileModal :input[data-role="seek-association-common-field"]').each(function () {
      $j(this).data('attributeName', this.name);
      this.name = '';
      batchSamplesForm.commonFieldElements.push($j(this));
    });

    var samplesTable;

    function initSamplesTable() {
      samplesTable = Samples.initTable($j('#data-file-samples-table'), true);
      // When at least one sample is selected, unlock step 3
      var handleRowSelect = function ( e, dt, type, indexes ) {
        var selectedRowData = samplesTable.rows({ selected: true }).data();

        batchSamplesForm.selectedItems = [];
        for(var i = 0; i < selectedRowData.length; i++) {
          batchSamplesForm.selectedItems.push({
            id: selectedRowData[i].id,
            title: selectedRowData[i].title
          });
        }

        if(selectedRowData.length > 0) {
          wizard.step(3).unlock();
        } else {
          wizard.step(3).lock();
        }
      };
      samplesTable.on('select', handleRowSelect);
      samplesTable.on('deselect', handleRowSelect);
    }

    initSamplesTable();

    $j('#add-batch-sample-btn').click(function () {
      batchSamplesForm.submit();
    });
    $j('#clear-all-samples-btn').click(function () {
      if(confirm("Are you sure you wish to remove all samples from this assay?")) {
        samplesList.removeAll();
      }
      return false;
    });

    // Wizard steps
    wizard = new Wizards.Wizard($j('#AddSamplesFromDataFileModal'));

    // On final step, show the confirm button
    wizard.step(3).onShow = function () {
      $j('#add-batch-sample-btn').show();
    };
    wizard.step(3).onHide = function () {
      $j('#add-batch-sample-btn').hide();
    };

    // Reset the wizard when the modal is closed
    $j('#AddSamplesFromDataFileModal').on('hide.bs.modal', function () {
      $j('[data-role="seek-association-filter-group"]', $j(this)).data('filterGroup').reset();
      samplesTable.rows().deselect();
      wizard.reset();
    });

    $j('#samples-select-data-file').on('click', '.selectable[data-role="seek-association-candidate"]', function () {
      var candidate = $j(this);
      candidate.spinner('add');
      $j.ajax('/data_files/'+$j(this).data('associationId')+'/samples_table', {
            success: function (data) {
              $j('#data-file-samples-table').html(data);
              initSamplesTable();
              wizard.step(2).unlock();
              wizard.gotoStep(2);
              candidate.spinner('remove');
            }
          }
      );

      return false;
    })
  });
</script>

app/views/samples/_association_preview.html.erb
<%= link_to '#', :class => "list-group-item selectable #{'list-group-item-success' if existing.include?(association_preview)}",
            'data-role' => 'seek-association-candidate',
            'data-association-id' => association_preview.id,
            'data-association-title' => association_preview.title do %>
    <%= association_preview.title %>
    <small>(<%= association_preview.sample_type.title %>)</small>
<% end %>

app/views/samples/_attribute_fields.html.erb
<% sample_type.sample_attributes.each do |attribute| %>
    <div class="form-group">
      <label><%= sample_attribute_title_and_unit(attribute) %></label><%= required_span if attribute.required? %>
      <%= sample_form_field_for_attribute(attribute) %>
    </div>
<% end %>

app/views/samples/_attribute_values.html.erb
<% sample.sample_type.sample_attributes.each do |attribute| %>
    <p>
      <label><%= sample_attribute_title_and_unit(attribute) %>:</label>
      <%= display_attribute(sample, attribute, link: true) %>
    </p>
<% end %>

app/views/samples/_form.html.erb
<div class="asset_form">
  <%= render partial: 'sample_error_messages', locals: { object: @sample } %>

  <p id="sample-type">
    <label>Sample type: </label> <%= link_to(h(@sample.sample_type.title), @sample.sample_type) %>
    <% if @sample.new_record? %>
      <span style="font-size:smaller">
        (<%= link_to('change', select_sample_types_path) %>)
      </span>
    <% end %>
    <%= f.hidden_field(:sample_type_id) %>
  </p>

  <div id="sample_attributes">
    <%= render :partial=>"sample_attributes_form",:locals=>{sample:@sample} %>
  </div>

  <div id="sample_extra_details">
    <% if show_form_manage_specific_attributes? && @sample.can_manage? -%>
      <%= render :partial => "projects/project_selector", :locals => { :resource => @sample,:allow_nil=> false} %>
      <%= render :partial => "assets/asset_form_bottom", :locals=>{:f=>f,attribution_enable:false,show_publications:false,sharing_link:false} %>
    <% end %>
  </div>

  <%= form_submit_buttons(@sample, validate:false) %>

</div>

app/views/samples/_resource_list_item.html.erb
<%= sample_type_list_item_attribute('Type',resource) %>

<%= render :partial=>"assets/resource_list_item_contributor_and_creators",:object=>resource -%>

app/views/samples/_resource_preview.html.erb
<strong>Preview Not Yet Implemented</strong>

app/views/samples/_sample_attributes_form.html.erb
<% if sample.sample_type %>

    <%= render :partial => "attribute_fields", :locals => {:sample_type => sample.sample_type} %>

<% end %>

app/views/samples/_sample_error_messages.html.erb
<% if object.errors.any? %>
    <div id="errorExplanation" class="errorExplanation">
      <h2><%= pluralize(object.errors.count, 'error') %> prohibited this sample from being saved</h2>
      <p>There were problems with the following fields:</p>
      <ul>
        <% object.errors.each do |attr, msg| %>
            <li><%= attr.to_s.sub(SampleAttribute::METHOD_PREFIX, '').humanize %> <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/samples/_table_view.html.erb
<% sample_type = samples.first.sample_type %>
<% shown_attributes = sample_type.sample_attributes.includes(:sample_attribute_type) %>
<% link ||= false %>
<% source_url ||= false %>

<div data-role="seek-association-candidate-list">
  <div class="table-responsive">
    <table class="table table-bordered samples-table" style="width: 100%" <%= "data-source-url=\"#{source_url}\"".html_safe if source_url %>>
      <% [:thead, :tfoot].each do |section| %>
          <%= content_tag(section) do %>
              <tr>
                <th>ID</th>
                <th>Title</th>
                <% shown_attributes.each do |attribute| %>
                    <th <%= 'data-title-column="true" ' if (attribute.is_title && link) -%>data-accessor-name="<%= attribute.accessor_name -%>" data-column-type="<%= attribute.sample_attribute_type.base_type-%>"><%= attribute.title %></th>
                <% end %>
              </tr>
          <% end %>
      <% end %>
      <% unless source_url %>
          <tbody>
          <% samples.each do |sample| %>
              <%= content_tag(:tr) do %>
                  <td><%= sample.id %></td>
                  <td><%= sample.title %></td>
                  <% shown_attributes.each do |attribute| %>
                      <% if (errors = sample.errors[attribute.method_name]).any? %>
                          <td class="sample-field-error">
                            <%# Wrapping <div> needed for popover to display properly %>
                            <%= content_tag(:div, data: {
                                toggle: 'popover',
                                content: errors.map { |e| "#{attribute.title} #{e}<br/>" }.join.html_safe }) do %>
                                <%= text_or_not_specified(sample.get_attribute_value(attribute), auto_link: link) %>
                            <% end %>
                          </td>
                      <% else %>
                          <td><%= display_attribute(sample, attribute, link: link) %></td>
                      <% end %>
                  <% end %>
              <% end %>
          <% end %>
          </tbody>
      <% end %>
    </table>
  </div>
  <% if samples.map { |s| s.errors.any? }.all? %>
      <%= modal(id: 'sample-error-modal') do %>
          <%= modal_header 'Errors' %>
          <%= modal_body {} %>
      <% end %>
  <% end %>
</div>

app/views/samples/edit.html.erb
<h1>Edit Sample</h1>

<%= form_for(@sample) do |f| %>
    <%= render :partial => "form", :locals => { :f => f } -%>
<% end %>

app/views/samples/manage.html.erb
<%= render partial:'assets/manage_form', locals:{resource:@sample, sharing_link:false} %>

app/views/samples/new.html.erb
<h1>New Sample</h1>

<%= form_for(@sample) do |f| %>
    <%= render :partial => "form", :locals => {:f => f} -%>
<% end %>

app/views/samples/show.html.erb
<%= render :partial => "general/item_title", :locals => {:item => @sample, :buttons_partial => 'assets/asset_buttons'} %>



<div class="row">
  <div class="col-md-9 col-sm-8 box_about_actor">

    <div class="row">
      <div class="col-md-6">
        <p>
          <label>Sample type:</label>
          <%= sample_type_link(@sample) %>
        </p>
        <% if @sample.originating_data_file %>
            <p>
              <label>Source data:</label>
              <%= link_to @sample.originating_data_file.title, @sample.originating_data_file %>
            </p>
        <% end %>
        <%= render :partial => "attribute_values", :locals => {:sample => @sample} %>
      </div>
    </div>
  </div>

  <div class="col-md-3 col-sm-4">
    <%= render :partial=>"assets/resource_main_content_right",:locals => { :resource => @sample } %>
  </div>
</div>


<%= render :partial=>"general/items_related_to",:object => @sample %>