config/routes.rb
  get 'index.html' => 'homes#index'
  get 'index' => 'homes#index'

  resource :favourites do
    collection do
      post :add
    end
    member do
      delete :delete
    end
  end

  resources :help, controller: 'help_documents', as: :help_documents do
    resources :attachments, controller: 'help_attachments', as: :help_attachments, only: [:create, :destroy] do
      member do
        get :download
      end
    end
    resources :images, controller: 'help_images', as: :help_images, only: [:create, :destroy] do
      member do
        get :view
      end
    end
  end
  resources :help_attachments, only: [:create, :destroy] do
    member do
      get :download
    end
  end
  resources :help_images, only: [:create, :destroy] do
    member do
      get :view
    end
  end

  resources :avatars
  resources :attachments
  resources :subscriptions
  resources :measured_items
  resources :saved_searches
  resources :uuids
  resources :compounds do
    collection do
      post :search_in_sabiork
    end
  end

  # resources :project_folders

  ### USERS AND SESSIONS ###

  resources :users do
    collection do
      get :activation_required
      get :forgot_password
      get :reset_password
      post :forgot_password
      post :hide_guide_box
      post :impersonate
      post :cancel_registration
      post :bulk_destroy
    end
    member do
      put :set_openid
      post :resend_activation_email
    end
    resources :oauth_sessions, only: [:index, :destroy]
    resources :identities, only: [:index, :destroy]
    resources :api_tokens, only: [:index, :create, :destroy]
  end

  resource :session do
    collection do
      get :index
      get :show
      get :auto_openid
    end
    member do
      get :show
    end
  end

  ### YELLOW PAGES ###

  resources :people, concerns: [:publishable] do
    collection do
      get :typeahead
      get :register
      get :current
      get :is_this_you
      get :get_work_group
      post :userless_project_selected_ajax
      post :items_for_result
      post :bulk_destroy
    end
    member do
      get :batch_publishing_preview
      get :requested_approval_assets
      post :gatekeeper_decide
      get :gatekeeper_decision_result
      get :waiting_approval_assets
      get :select
      get :items
    end
    resources :projects, :institutions, :assays, :studies, :investigations, :models, :sops, :workflows, :nodes, :data_files, :presentations, :publications, :documents, :events, :samples, :specimens, :strains, :collections, only: [:index]
    resources :avatars do
      member do
        post :select
      end
    end
  end

  resources :projects do
    collection do
      get :request_institutions
      get :manage
      post :items_for_result
      get :guided_join
      get :guided_create
      post :request_join
      post :request_create
    end
    member do
      get :asset_report
      get :admin_members
      get :admin_member_roles
      get :storage_report
      post :update_members
      post :request_membership
      get :overview
      get :administer_join_request
      post :respond_join_request
    end
    resources :people, :institutions, :assays, :studies, :investigations, :models, :sops, :workflows, :nodes, :data_files, :presentations,
              :publications, :events, :samples, :specimens, :strains, :search, :organisms, :human_diseases, :documents, :collections, only: [:index]

    resources :openbis_endpoints do
      collection do
        get :test_endpoint
        get :fetch_spaces
        get :browse
      end
    end
    resources :avatars do
      member do
        post :select
      end
    end
    resources :folders do
      collection do
        post :nuke
      end
      member do
        post :remove_asset
        get :display_contents
        post :move_asset_to
        post :create_folder
        post :set_project_folder_title
        post :set_project_folder_description
      end
    end
    concerns :has_dashboard, controller: :project_stats
  end

  resources :openbis_endpoints do
    get :test_endpoint, on: :member
    get :fetch_spaces, on: :member
    get :refresh, on: :member
    get :reset_fatals, on: :member
    resources :openbis_experiments do
      get :refresh, on: :member
      post :register, on: :member
      post :batch_register, on: :collection
    end
    resources :openbis_zamples do
      get :refresh, on: :member
      post :register, on: :member
      post :batch_register, on: :collection
    end
    resources :openbis_datasets do
      get :refresh, on: :member
      post :register, on: :member
      get :show_dataset_files, on: :member
      post :batch_register, on: :collection
    end
  end

  resources :institutions do
    collection do
      post :items_for_result
      get  :typeahead
    end
    resources :people, :projects, :specimens, only: [:index]
    resources :avatars do
      member do
        post :select
      end
    end
  end

  ### ISA ###

  resources :investigations, concerns: [:publishable, :has_snapshots, :isa] do
    resources :people, :projects, :assays, :studies, :models, :sops, :workflows, :nodes, :data_files, :publications, :documents, only: [:index]
    member do
      get :export_isatab_json
    end
  end

  resources :studies, concerns: [:publishable, :has_snapshots, :isa] do
    collection do
      post :investigation_selected_ajax
    end
    resources :people, :projects, :assays, :investigations, :models, :sops, :workflows, :nodes, :data_files, :publications, :documents, only: [:index]
  end

  resources :assays, concerns: [:publishable, :has_snapshots, :isa] do
    resources :nels, only: [:index] do
      collection do
        get :projects
        get :datasets
        get :dataset
        post :register
      end
    end
    resources :people, :projects, :investigations, :samples, :studies, :models, :sops, :workflows, :nodes, :data_files, :publications, :documents, :strains, :organisms, :human_diseases, only: [:index]
  end

  # to be removed as STI does not work in too many places
  # resources :openbis_assays, controller: 'assays', type: 'OpenbisAssay'

  ### ASSAY AND TECHNOLOGY TYPES ###

  resources :suggested_assay_types
  resources :suggested_modelling_analysis_types, path: :suggested_assay_types, controller: :suggested_assay_types
  resources :suggested_technology_types

  ### ASSETS ###

  resources :data_files, concerns: [:has_content_blobs, :has_versions, :has_doi, :publishable, :asset] do
    collection do
      get :filter
      post :upload_for_tool
      post :upload_from_email
      get :provide_metadata
      post :create_content_blob
      post :rightfield_extraction_ajax
      post :create_metadata
    end
    member do
      get :plot
      get :explore
      get :samples_table
      get :select_sample_type
      get :confirm_extraction
      get :extraction_status
      post :extract_samples
      delete :cancel_extraction
      get :destroy_samples_confirm
      post :retrieve_nels_sample_metadata
      get :retrieve_nels_sample_metadata
    end
    resources :studied_factors do
      collection do
        post :create_from_existing
      end
    end
    resources :people, :projects, :investigations, :assays, :samples, :studies, :publications, :events, :collections, only: [:index]
  end

  resources :presentations, concerns: [:has_content_blobs, :publishable, :has_versions, :asset] do
    resources :people, :projects, :publications, :events, :collections, only: [:index]
  end

  resources :models, concerns: [:has_content_blobs, :publishable, :has_doi, :has_versions, :asset] do
    member do
      get :compare_versions
      post :compare_versions
      get :visualise
      post :submit_to_sycamore
      post :export_as_xgmml
      post :execute
      get :simulate
      post :simulate
    end
    resources :model_images do
      collection do
        post :new
      end
      member do
        post :select
      end
    end
    resources :people, :projects, :investigations, :assays, :studies, :publications, :events, :collections, only: [:index]
  end

  resources :sops, concerns: [:has_content_blobs, :publishable, :has_doi, :has_versions, :asset] do
    resources :experimental_conditions do
      collection do
        post :create_from_existing
      end
    end
    resources :people, :projects, :investigations, :assays, :samples, :studies, :publications, :events, :workflows, :collections, only: [:index]
  end

  resources :workflows, concerns: [:has_content_blobs, :publishable, :has_doi, :has_versions, :asset] do
    collection do
      post :create_content_blob
      post :create_ro_crate
      get :provide_metadata
      post :metadata_extraction_ajax
      post :create_metadata
    end
    member do
      get :diagram
      get :ro_crate
    end
    resources :people, :projects, :investigations, :assays, :samples, :studies, :publications, :events, :sops, :collections, only: [:index]
  end

  resources :nodes, concerns: [:has_content_blobs, :publishable, :has_doi, :has_versions, :asset] do
    resources :people, :projects, :investigations, :assays, :samples, :studies, :publications, :events, :collections, only: [:index]
  end

  resources :content_blobs, except: [:show, :index, :update, :create, :destroy] do
    collection do
      post :examine_url
    end
  end
  resources :programmes do
    resources :avatars do
      member do
        post :select
      end
    end
    collection do
      post :items_for_result
      get :awaiting_activation
      get :administer_create_project_request
      post :respond_create_project_request
    end
    member do
      get :activation_review
      put :accept_activation
      put :reject_activation
      get :reject_activation_confirmation
      get :storage_report
    end
    resources :people, :projects, :institutions, :investigations, :studies, :assays,

app/controllers/organisms_controller.rb
class OrganismsController < ApplicationController

  include Seek::DestroyHandling

  before_action :organisms_enabled?
  before_action :find_requested_item, :only=>[:show,:edit,:visualise,:destroy, :update]
  before_action :login_required,:except=>[:show,:index,:visualise]
  before_action :can_manage?,:only=>[:edit,:update]
  before_action :auth_to_create, :only=>[:new,:create, :destroy]
  before_action :find_assets, only: [:index]

  skip_before_action :project_membership_required

  cache_sweeper :organisms_sweeper,:only=>[:update,:create,:destroy]

  include BioPortal::RestAPI
  include Seek::ExternalServiceWrapper
  include Seek::IndexPager
  include Seek::BreadCrumbs

  api_actions :index, :show

  def show
    respond_to do |format|
      format.html
      format.xml
      format.rdf { render :template=>'rdf/show'}
      format.json {render json: @organism, include: [params[:include]]}
    end
  end

  def visualise
    @no_sidebar=true
    respond_to do |format|
      format.html
    end
  end

  def new
    @organism=Organism.new
    respond_to do |format|
      format.html
    end
  end

  def search_ajax
    pagenum=params[:pagenum]
    pagenum||=1
    search_term=params[:search_term]
    results, pages, error = nil
    wrap_service('BioPortal', proc { |m| error = m }) do
      results,pages = search search_term,{:isexactmatch=>0,:pagesize=>100,:page=>pagenum,:ontologies=>"NCBITAXON",:apikey=>Seek::Config.bioportal_api_key}
    end
    if results
      render :partial => "search_results",
                        :object => results, :locals => { :pages => pages, :pagenum => pagenum, :search_term => search_term }
    else
      render :partial => "search_error", :locals => { :text => error || "Nothing found" }
    end
  end

  def create
    @organism = Organism.new(organism_params)
    respond_to do |format|
      if @organism.save
        flash[:notice] = 'Organism was successfully created.'
        format.html { redirect_to organism_path(@organism) }
        format.xml  { head :ok }
        format.json {render json: @organism, status: :created, location: @organism, include: [params[:include]]}
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @organism.errors, :status => :unprocessable_entity }
        format.json  { render json: @organism.errors, status: :unprocessable_entity }
      end
    end
  end

  def update

    respond_to do |format|
      if @organism.update_attributes(organism_params)
        flash[:notice] = 'Organism was successfully updated.'
        format.html { redirect_to organism_path(@organism) }
        format.xml  { head :ok }
        format.json {render json: @organism, include: [params[:include]]}
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @organism.errors, :status => :unprocessable_entity }
        format.json  { render json: @organism.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    respond_to do |format|
      format.html
      format.xml {render :xml=>@organism}
    end
  end

  private

  def organism_params
    params.require(:organism).permit(:title, :ontology_id, :concept_uri)
  end

  def can_manage?
    unless @organism.can_manage?
      error("Admin rights required", "is invalid (not admin)")
      false
    end
    true
  end

end

app/helpers/organisms_helper.rb
module OrganismsHelper
  # helper method to help consilidate the fact that organisms are both tags and model entities
  def organism_link_to(model_or_tag)
    return "<span class='none_text'>No Organism specified</span>" if model_or_tag.nil?
    if model_or_tag.instance_of?(Organism)
      link_to model_or_tag.title.capitalize, model_or_tag
    end
  end

  def organisms_link_list(organisms)
    link_list = ''
    link_list = "<span class='none_text'>No Organisms specified</span>" if organisms.empty?
    organisms.each do |o|
      link_list << organism_link_to(o)
      link_list << ', ' unless o == organisms.last
    end
    link_list.html_safe
  end

  def link_to_ncbi_taxonomy_browser(organism, text, html_options = {})
    html_options[:alt] ||= text
    html_options[:title] ||= text
    id = organism.ncbi_id
    link_to text, "http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=info&id=#{id}", html_options
  end

  def delete_organism_icon(organism)
    if organism.can_delete?
      image_tag_for_key('destroy', organism_path(organism), 'Delete Organism', { data: { confirm: 'Are you sure?' }, method: :delete }, 'Delete Organism')
    else
      explanation = 'Unable to delete an Organism that is associated with other items.'
      html = "<span class='disabled_icon disabled' onclick='javascript:alert(\"#{explanation}\")' data-tooltip='#{tooltip(explanation)}' >" + image('destroy', alt: 'Delete', class: 'disabled') + ' Delete Organism</span>'
      html.html_safe
    end
  end

  # takes an array of [organism,strain] where strain can be nil if not defined
  def list_organisms_and_strains(organism_and_strains, none_text = 'Not specified')
    result = ''
    result = "<span class='none_text'>#{none_text}</span>" if organism_and_strains.empty?
    organism_and_strains.each do |os|
      organism = os[0]
      strain = os[1]
      unless strain.nil? && organism.nil?
        result += organism_and_strain strain, organism
        result += ', ' unless os == organism_and_strains.last
      end
    end
    result.html_safe
  end

  def organism_and_strain(strain, organism = strain.organism, none_text = 'Not specified')
    result = ''
    if organism
      result << link_to(h(organism.title), organism)
      if strain && !strain.is_dummy? && strain.can_view?
        result << " : <span class='strain_info'>#{link_to strain.info, strain}</span>"
      elsif strain && !strain.is_dummy? && !strain.can_view?
        result << hidden_items_html([strain], ' : hidden strain')
      end
    end
    result.empty? ? "<span class='none_text'>#{none_text}</span>".html_safe : result.html_safe
  end

  def can_create_organisms?
    Organism.can_create?
  end

  def bioportal_search_enabled?
    !Seek::Config.bioportal_api_key.blank?
  end
end

app/views/organisms/_bioportal_concept_details.html.erb
<%# required because earlier cached concept hash may not include this key -%>
<% concept[:related_synonyms] ||= [] %>

<b>Synonyms (<%= concept[:synonyms].count -%>) </b>
<% if concept[:synonyms].empty? -%>
    <p class="none_text">None defined</p>
<% else -%>
    <p><%= concept[:synonyms].join(", ") %></p>
<% end -%>
<br/>
<b>Definitions (<%= concept[:definitions].count -%>) </b>
<% if concept[:definitions].empty? -%>
    <p class="none_text">None defined</p>
<% else -%>
    <p><%= concept[:definitions].join(", ") %></p>
<% end -%>

app/views/organisms/_form.html.erb
<%
   details_active = (params[:action] == "edit") || @organism.errors.any?
   details_active = details_active || !bioportal_search_enabled?

   if details_active
     search_status=""
     details_status="active"
   else
     search_status="active"
     details_status=""
   end

%>

<div class="container">
  <ul class="nav nav-tabs">
    <li role="search" class="<%= search_status %>"><a data-toggle="tab" href="#search">Search</a></li>
    <li role="details" class="<%= details_status %>"><a data-toggle="tab" href="#details">Organism details</a></li>
  </ul>

  <div class="tab-content">
    <div class="tab-pane <%= search_status %>" id="search">
      <% if bioportal_search_enabled? %>
          <div id="organism-search">
            <%= render :partial => "search_bioportal" %>
          </div>
      <% elsif admin_logged_in? %>
          <div class="alert alert-warning" role="alert">
            If you wish to add the ability to search the NCBI taxonomy, please register with
            http://bioportal.bioontology.org to get an API key.<br/>
            You can then add the API key under Server admin -> Site configuration -> Additional settings
          </div>
      <% end %>
    </div>
    <div class="tab-pane <%= details_status %>" id="details">
      <div id="organism-attributes">
        <%= render :partial => "organism_attributes_form" %>
      </div>
    </div>
  </div>
</div>

app/views/organisms/_organism_attributes_form.html.erb
<%= panel("Organism details") do %>
    <%= form_for(@organism) do |f| %>

        <%= f.error_messages -%>

        <div class="form-group">
          <%= f.label :display_name, class: 'required' -%>
          <%= f.text_field :title, :class => "form-control" -%>
        </div>
        <%= f.hidden_field :ontology_id -%>

        <div class="form-group">
          <label>NCBI Taxonomy URI</label>
          <span class='help-block'>A valid NCBI taxonomy URI is required. This can be of the form http://purl.bioontology.org/ontology/NCBITAXON/&lt;Number&gt; or https://identifiers.org/taxonomy/&lt;Number&gt;<br/>
          You can just enter the NCBI number, and it will automatically be turned into a valid URI.
          </span>
          <%= f.text_field :concept_uri, :class => "form-control" -%>
        </div>

        <%= f.submit @organism.id ? "Update" : "Create", data: { disable_with: @organism.id ? "Updating..." : "Creating..." },
                     :class => 'btn btn-primary' -%>
    <% end %>
<% end %>

app/views/organisms/_resource_actions_td.html.erb
<% cache "rli_actions_#{resource.cache_key}_#{current_user_id}", skip_digest: true do -%>
    <% if resource.can_manage? -%>
      <%= button_link_to 'Manage', 'manage', edit_organism_path(resource), class: 'btn-xs' -%>
    <% end -%>

    <% if resource.can_delete? -%>
        <%= button_link_to 'Delete', 'destroy', organism_path(resource), data: { confirm: 'Are you sure?' },
                           method: :delete, class: 'btn-xs' -%>
    <% end -%>
<% end -%>

app/views/organisms/_resource_list_item.html.erb
<%= list_item_attribute "Taxonomy URI",text_or_not_specified(resource.concept_uri) -%>
<% unless (concept = resource.concept).nil? %>
  <%= list_item_attribute 'Synonyms', concept[:synonyms].join(', ') if concept[:synonyms].any? -%>
  <%= list_item_attribute 'Definitions', concept[:definitions].join(', ') if concept[:definitions].any? -%>
<% end %>

app/views/organisms/_search_bioportal.html.erb
<%= panel('Search the NCBI Ontology') do %>
    <p>
      Search below for the name of the organism. You can use its official name, or its common name or one of its synonyms.
    </p>
    <%= form_tag_with_callbacks(search_ajax_organisms_path,
                                { id: "search_organism",
                                  before: "$j('#search_results').spinner('add');",
                                  update: { success: 'search_results', error: 'search_results' },
                                  remote: true }) do -%>

        <%= hidden_field_tag :pagenum, 1 -%>

        <div class="form-group">
          <label>Search for</label>
          <%= text_field_tag :search_term, @organism.title, :class => "form-control" %>
        </div>

        <%= submit_tag "Search", data: { disable_with: 'Searching ...' }, :class => 'btn btn-primary' %>
    <% end -%>

    <div id="search_results">

    </div>
<% end %>

<script type="text/javascript">
    function add_concept(label, ont_acronym, conc_id) {
        $j('#organism_title').val(label);
        $j('#organism_ontology_id').val(ont_acronym);
        $j('#organism_concept_uri').val(conc_id);
        //jump to the details tab and highlight the fields
        $j('.nav-tabs a[href="#details"]').tab('show');
        $j("#organism_title").highlight();
        $j("#organism_concept_uri").highlight();
    }
</script>

app/views/organisms/_search_results.html.erb
<% if !search_results.empty? -%>
  <p><%= link_to image("arrow_left"),  url_for(:action => :search_ajax, :controller => :organisms, :pagenum => pagenum.to_i-1, :search_term => search_term),
                 method: :post, remote: true, class: 'bioportal-pager-link' unless pagenum.to_i <= 1 -%>
    <%= "Page #{pagenum.to_s}  of #{pages.to_s}" -%>
    <%= link_to image("arrow_right"), url_for(:action => :search_ajax, :controller => :organisms, :pagenum => pagenum.to_i+1, :search_term => search_term),
                method: :post, remote: true, class: 'bioportal-pager-link' unless pagenum.to_i >= pages.to_i -%>
    </p>
    <div id="organism-search-results">
      <table class="table">
        <thead>
        <tr>
          <th id="organism-name">
            Organism (click to select)
          </th>
          <th id="organism-synonyms">Synonyms</th>
          <th id="organism-id">Taxonomy id</th>
        </tr>
        </thead>
        <tbody>
        <% search_results.each do |result| %>
            <tr>
              <td>
                <%= link_to(result[:preferred_label], '#', onclick: "add_concept('#{result[:preferred_label]}','#{result[:ontology_acronym]}','#{result[:class_id]}'); return false;") -%>
              </td>
              <td><%= h(result[:synonyms].join(", ")) %></td>
              <td><%= result[:class_id] %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  <script>
    $j('.bioportal-pager-link').bind('ajax:beforeSend', function () {
        $j('#search_results').spinner('add');
    }).bind('ajax:complete', function (e, xhr) {
        $j('#search_results').html(xhr.responseText);
    })
  </script>
<% elsif !search_term.blank? %>
    <br/>
    <span class="none_text">No matches found for <b><%= h(search_term) -%></b></span>
<% end -%>

app/views/organisms/_select_organism.html.erb
<% if Seek::Config.organisms_enabled %>
    <%
        organisms = current_user.person.projects.collect{|p| p.organisms}.flatten.uniq.sort_by(&:title)
    %>

    <%= folding_panel("Details about the organism") do %>
        <div class="form-group">
            <label>Organism</label>
            <%= select model_class.name.underscore.to_sym, :organism_id,
                       organisms.collect{|o| [o.title.capitalize,o.id]},
                       {:include_blank=>"Not specified"}, {:class => 'form-control'} -%>
        </div>
    <% end %>
<% end %>

app/views/organisms/_strain_information_row.html.erb
<% strain = strain_information_row -%>
<tr>
  <td><%= link_to strain.title,strain -%></td>
  <td><%= text_or_not_specified(strain.provider_name) -%></td>
  <td><%= text_or_not_specified(strain.provider_id) -%></td>
  <td><%= text_or_not_specified(strain.genotype_info) -%></td>
  <td><%= text_or_not_specified(strain.phenotype_info) -%></td>
  <td><%= text_or_not_specified(strain.synonym) -%></td>
  <td><%= text_or_not_specified(strain.comment,{:none_text=>"None"}) -%></td>
  <td><%= strain.parent.nil? ? text_or_not_specified(strain.parent) : link_to(strain.parent.title,strain.parent) -%></td>
</tr>

app/views/organisms/edit.html.erb
<h1>Editing the organism <%= link_to @organism.title,@organism -%></h1>

<%= render :partial=>"form" -%>

app/views/organisms/index.html.erb
<%= render partial: "general/index", locals: { new_item_label: "New Organism" } %>

app/views/organisms/new.html.erb
<h1>Add a new organism</h1>

<%= render :partial=>"form" -%>

app/views/organisms/show.html.erb
<% if admin_logged_in? -%>
    <% content_for(:buttons) do -%>
        <%= item_actions_dropdown do %>
          <li><%= image_tag_for_key('edit', edit_organism_path(@organism), "Edit Organism", nil, 'Edit Organism') -%></li>
          <li><%= image_tag_for_key('new', new_organism_path, "Add Organism", nil, 'Add Organism') -%></li>
          <li><%= delete_organism_icon(@organism)%></li>
        <% end %>
    <% end %>
<% elsif can_create_organisms? %>
    <% content_for(:buttons) do -%>
        <%= item_actions_dropdown do %>
            <li><%= image_tag_for_key('new', new_organism_path, "Add Organism", nil, 'Add Organism') -%></li>
            <li><%= delete_organism_icon(@organism)%></li>
        <% end %>
    <% end %>
<% end %>


<%= render :partial => "general/item_title",:locals=>{:item=>@organism} %>

<div class="show_basic">

  <% if @organism.concept -%>
    <h2>Details about this organism</h2>
    <%= render :partial=>"bioportal_concept_details",:locals=>{:concept=>@organism.concept} -%>
    <br/>
  <% end -%>

  <% if @organism.ncbi_id %>
    <%= link_to_ncbi_taxonomy_browser @organism,"NCBI taxonomy browser",:popup=>true %>
  <% end %>

  <h2>Strain details</h2>
  <table class="strain_list" style="width:100%;">
  <thead>
    <th>Name</th>
    <th>Provider name</th>
    <th>Provider's strain ID</th>
    <th>Genotypes</th>
    <th>Phenotypes</th>
    <th>Synonym</th>
    <th>Comments</th>
    <th>Based on</th>
  </thead>
  <%= render :partial=>"strain_information_row", :collection=>@organism.strains.without_default.select(&:can_view?) -%>
  </table>
<%= render :partial=>"general/items_related_to",:object => @organism %>
</div>

app/views/organisms/visualise.html.erb
<style>

  #bioportal_visualise_container {
      height: 70em;
      padding: 2em;
  }
  iframe#bioportal_visualisation {
      padding:0.5em;
      border: solid 1px #bbb;
      width: 100%;
      height: 80%;
      overflow: visible;
  }
</style>
<ul class="sectionIcons">
  <li>
    <%= image_tag_for_key('back', organism_path(@organism), nil, nil, "Back to #{@organism.title}") -%>
  </li>
</ul>
<br/>
<h1>Visualising the term <em><%= @organism.concept_uri %></em> defined for the organism <em><%= @organism.title %></em></h1>
<div id="bioportal_visualise_container">
    <%= visualise_ontology @organism,:show_concept=>true,:apikey=>Seek::Config.bioportal_api_key %>
</div>