config/routes.rb
SEEK::Application.routes.draw do
  use_doorkeeper do
    controllers applications: 'oauth_applications'
    controllers authorized_applications: 'authorized_oauth_applications'
    controllers authorizations: 'oauth_authorizations'
  end
  mount MagicLamp::Genie, at: (SEEK::Application.config.relative_url_root || '/') + 'magic_lamp' if defined?(MagicLamp)
  # mount Teaspoon::Engine, :at => (SEEK::Application.config.relative_url_root || "/") + "teaspoon" if defined?(Teaspoon)

  # Concerns
  concern :has_content_blobs do
    member do
      get :download
    end
    resources :content_blobs do
      member do
        get :view_pdf_content
        get :view_content
        get :get_pdf
        get :download
      end
    end
  end

  concern :has_dashboard do |stats_options|
    resources :stats, stats_options.reverse_merge(only: []) do
      collection do
        get :dashboard
        get :contributions
        get :asset_activity
        get :contributors
        get :asset_accessibility
        post :clear_cache
      end
    end
  end

  concern :publishable do
    member do
      post :check_related_items
      post :check_gatekeeper_required
      get :published
      post :publish_related_items
      post :publish
    end
  end

  concern :has_versions do
    member do
      post :new_version
      post :edit_version_comment
      delete :destroy_version
    end
  end

  concern :has_snapshots do
    resources :snapshots, only: [:show, :new, :create, :destroy], concerns: [:has_doi] do
      member do
        get :download
        get :export, action: :export_preview
        post :export, action: :export_submit
      end
    end
  end

  concern :has_doi do
    member do
      get :mint_doi_confirm
      post :mint_doi
    end
  end

  concern :asset do
    collection do
      get :typeahead
      get :preview
      post :items_for_result # Faceted browsing
    end
    member do
      post :request_contact
      post :update_annotations_ajax
      get :manage
      patch :manage_update
    end
  end

  concern :isa do
    collection do
      get :typeahead
      get :preview
      post :items_for_result # Faceted browsing
    end
    member do
      post :update_annotations_ajax
      get :manage
      patch :manage_update
      get :new_object_based_on_existing_one
    end
  end

  resources :scales do
    collection do
      post :search
    end
  end

  ### GENERAL PAGES ###

  root to: 'homes#index'

  resource :admin, controller: 'admin' do
    collection do
      get :index
      get :tags
      get :features_enabled
      get :rebrand
      get :home_settings
      get :pagination
      get :settings
      get :get_stats
      get :registration_form
      get :edit_tag
      post :update_home_settings
      post :restart_server
      post :restart_delayed_job
      post :update_admins
      post :update_rebrand
      post :test_email_configuration
      post :update_settings
      post :update_features_enabled
      post :update_pagination
      post :delete_tag
      post :edit_tag
      post :update_imprint_setting
      post :clear_failed_jobs
    end
    concerns :has_dashboard, controller: :stats
  end

  resource :home do
    member do
      get :index
      get :feedback
      get :funding
      post :send_feedback
      get :imprint
      get :terms
      get :privacy
      get :about
      get :create_or_join_project
    end
  end

  get 'funding' => 'homes#funding', as: :funding
  get 'index.html' => 'homes#index'
  get 'index' => 'homes#index'

  resource :favourites do
    collection do
      post :add
    end
    member do
      delete :delete
    end
  end

  resources :help, controller: 'help_documents', as: :help_documents do
    resources :attachments, controller: 'help_attachments', as: :help_attachments, only: [:create, :destroy] do
      member do
        get :download
      end
    end
    resources :images, controller: 'help_images', as: :help_images, only: [:create, :destroy] do
      member do
        get :view
      end
    end
  end
  resources :help_attachments, only: [:create, :destroy] do
    member do
      get :download
    end
  end
  resources :help_images, only: [:create, :destroy] do
    member do
      get :view
    end
  end

  resources :avatars
  resources :attachments
  resources :subscriptions
  resources :measured_items
  resources :saved_searches
  resources :uuids
  resources :compounds do
    collection do
      post :search_in_sabiork
    end
  end

  # resources :project_folders

  ### USERS AND SESSIONS ###

  resources :users do
    collection do
      get :activation_required
      get :forgot_password
      get :reset_password
      post :forgot_password
      post :hide_guide_box
      post :impersonate
      post :cancel_registration
      post :bulk_destroy
    end
    member do
      put :set_openid
      post :resend_activation_email
    end
    resources :oauth_sessions, only: [:index, :destroy]
    resources :identities, only: [:index, :destroy]
    resources :api_tokens, only: [:index, :create, :destroy]
  end

  resource :session do
    collection do
      get :index
      get :show
      get :auto_openid
    end
    member do
      get :show
    end
  end

  ### YELLOW PAGES ###

  resources :people, concerns: [:publishable] do
    collection do
      get :typeahead
      get :register
      get :current
      get :is_this_you
      get :get_work_group
      post :userless_project_selected_ajax
      post :items_for_result
      post :bulk_destroy
    end
    member do
      get :batch_publishing_preview
      get :requested_approval_assets
      post :gatekeeper_decide
      get :gatekeeper_decision_result
      get :waiting_approval_assets
      get :select
      get :items
    end
    resources :projects, :institutions, :assays, :studies, :investigations, :models, :sops, :workflows, :nodes, :data_files, :presentations, :publications, :documents, :events, :samples, :specimens, :strains, :collections, only: [:index]
    resources :avatars do
      member do
        post :select
      end
    end
  end

  resources :projects do
    collection do
      get :request_institutions
      get :manage
      post :items_for_result
      get :guided_join
      get :guided_create
      post :request_join
      post :request_create
    end
    member do
      get :asset_report
      get :admin_members
      get :admin_member_roles
      get :storage_report
      post :update_members
      post :request_membership
      get :overview
      get :administer_join_request
      post :respond_join_request
    end
    resources :people, :institutions, :assays, :studies, :investigations, :models, :sops, :workflows, :nodes, :data_files, :presentations,
              :publications, :events, :samples, :specimens, :strains, :search, :organisms, :human_diseases, :documents, :collections, only: [:index]

    resources :openbis_endpoints do
      collection do
        get :test_endpoint
        get :fetch_spaces
        get :browse
      end
    end
    resources :avatars do
      member do
        post :select
      end
    end
    resources :folders do
      collection do
        post :nuke
      end
      member do
        post :remove_asset
        get :display_contents
        post :move_asset_to
        post :create_folder
        post :set_project_folder_title
        post :set_project_folder_description
      end
    end
    concerns :has_dashboard, controller: :project_stats
  end

  resources :openbis_endpoints do
    get :test_endpoint, on: :member
    get :fetch_spaces, on: :member
    get :refresh, on: :member
    get :reset_fatals, on: :member
    resources :openbis_experiments do
      get :refresh, on: :member
      post :register, on: :member
      post :batch_register, on: :collection
    end
    resources :openbis_zamples do
      get :refresh, on: :member
      post :register, on: :member
      post :batch_register, on: :collection
    end
    resources :openbis_datasets do
      get :refresh, on: :member
      post :register, on: :member
      get :show_dataset_files, on: :member
      post :batch_register, on: :collection
    end
  end

  resources :institutions do
    collection do
      post :items_for_result
      get  :typeahead
    end
    resources :people, :projects, :specimens, only: [:index]
    resources :avatars do
      member do
        post :select
      end
    end
  end

  ### ISA ###

  resources :investigations, concerns: [:publishable, :has_snapshots, :isa] do
    resources :people, :projects, :assays, :studies, :models, :sops, :workflows, :nodes, :data_files, :publications, :documents, only: [:index]
    member do
      get :export_isatab_json
    end
  end

  resources :studies, concerns: [:publishable, :has_snapshots, :isa] do
    collection do
      post :investigation_selected_ajax
    end
    resources :people, :projects, :assays, :investigations, :models, :sops, :workflows, :nodes, :data_files, :publications, :documents, only: [:index]
  end

  resources :assays, concerns: [:publishable, :has_snapshots, :isa] do
    resources :nels, only: [:index] do
      collection do
        get :projects
        get :datasets
        get :dataset
        post :register
      end
    end
    resources :people, :projects, :investigations, :samples, :studies, :models, :sops, :workflows, :nodes, :data_files, :publications, :documents, :strains, :organisms, :human_diseases, only: [:index]
  end

  # to be removed as STI does not work in too many places
  # resources :openbis_assays, controller: 'assays', type: 'OpenbisAssay'

  ### ASSAY AND TECHNOLOGY TYPES ###

  resources :suggested_assay_types
  resources :suggested_modelling_analysis_types, path: :suggested_assay_types, controller: :suggested_assay_types
  resources :suggested_technology_types

  ### ASSETS ###

  resources :data_files, concerns: [:has_content_blobs, :has_versions, :has_doi, :publishable, :asset] do
    collection do
      get :filter

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user

  def self.from_omniauth(auth)
    Identity.where(provider: auth.provider, uid: auth.uid).first_or_initialize
  end
end

app/controllers/identities_controller.rb
class IdentitiesController < ApplicationController
  before_action :find_and_check_user

  include Seek::BreadCrumbs

  skip_before_action :add_breadcrumbs, only: :destroy

  def index
    @identities = @user.identities
  end

  def destroy
    @identity = @user.identities.find(params[:id])

    @identity.destroy
    flash[:notice] = "Unlinked #{t("login.#{@identity.provider}")} identity from your account."
    redirect_to user_identities_path(@user)
  end

  private

  def find_and_check_user
    @user = User.find(params[:user_id])
    @parent_resource = @user&.person

    if current_user != @user
      error("User not found (id not authorized)", "is invalid (not owner)")
      false
    end
  end
end

app/views/identities/_ldap_form.html.erb
<%= form_tag omniauth_callback_path(:ldap) do %>
  <% original_path ||= request.original_fullpath %>
  <%= hidden_field_tag "called_from[path]", original_path -%>
  <%= hidden_field_tag "called_from[controller]", controller.controller_name -%>
  <%= hidden_field_tag "called_from[action]", controller.action_name -%>
  <%= hidden_field_tag "called_from[id]", params[:id] -%>

  <div class="form-group">
    <label>Username</label>
    <%= text_field_tag 'username', nil, class: 'form-control', placeholder: 'LDAP username' -%>
  </div>

  <div class="form-group">
    <label>Password</label>
    <%= password_field_tag 'password', nil, class: 'form-control', id: "login_ldap_password", placeholder: 'LDAP password' -%>
  </div>

  <div class="form-group">
    <%= submit_tag "Log in", class: 'btn btn-default', id: "login_ldap_button" %>
  </div>
<% end #form %>

app/views/identities/index.html.erb
<%= button_link_to('Return to profile', 'back', person_path(@user.person)) -%>
<div class="pull-right">
  <%= dropdown_button('Add identity', 'add') do %>
    <% if Seek::Config.omniauth_elixir_aai_enabled %>
      <li><%= link_to(t("login.elixir_aai"), omniauth_authorize_path(:elixir_aai), method: :post) -%></li>
    <% end %>
    <% if Seek::Config.omniauth_ldap_enabled %>
      <li><%= link_to(t("login.ldap"), '#', 'data-toggle' => 'modal', 'data-target' => "#ldap-form") -%></li>
    <% end %>
    <% if Seek::Config.omniauth_github_enabled %>
      <li><%= link_to(t("login.github"), omniauth_authorize_path(:github), method: :post) -%></li>
    <% end %>
  <% end %>
</div>

<h1>Identities</h1>

<%= modal(id: 'ldap-form', size: 'm') do %>
  <%= modal_header("LDAP Authentication") %>
  <%= modal_body do %>
    <%= render partial: 'identities/ldap_form' %>
  <% end %>
<% end %>

<div class="row">
  <div class="col-sm-12">
    <div class="alert alert-warning" role="alert">
      To avoid being locked out of your account, please ensure you either:
      <ul>
        <li>Keep at least 1 identity</li>
        <li>Know your <%= Seek::Config.application_name -%> password</li>
        <li>Have access to your registered email address: <%= link_to @user.person.email, edit_person_path(@user.person, anchor: 'person_email') -%></li>
      </ul>
    </div>

    <table class="table">
      <thead>
      <tr>
        <th>Provider</th>
        <th>UID</th>
        <th>Created At</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @identities.each do |identity| %>
        <tr>
          <td><%= t("login.#{identity.provider}") %></td>
          <td><%= content_tag(:pre, identity.uid) %></td>
          <td><%= identity.created_at %></td>
          <td>
            <%= link_to 'Unlink', user_identity_path(current_user, identity),
                        method: :delete,
                        data: { confirm: 'Are you sure you want to unlink this identity from your account?' },
                        class: 'btn btn-xs btn-danger' %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>