config/routes.rb
  resources :suggested_modelling_analysis_types, path: :suggested_assay_types, controller: :suggested_assay_types
  resources :suggested_technology_types

  ### ASSETS ###

  resources :data_files, concerns: [:has_content_blobs, :has_versions, :has_doi, :publishable, :asset] do
    collection do
      get :filter
      post :upload_for_tool
      post :upload_from_email
      get :provide_metadata
      post :create_content_blob
      post :rightfield_extraction_ajax
      post :create_metadata
    end
    member do
      get :plot
      get :explore
      get :samples_table
      get :select_sample_type
      get :confirm_extraction
      get :extraction_status
      post :extract_samples
      delete :cancel_extraction
      get :destroy_samples_confirm
      post :retrieve_nels_sample_metadata
      get :retrieve_nels_sample_metadata
    end
    resources :studied_factors do
      collection do
        post :create_from_existing
      end
    end
    resources :people, :projects, :investigations, :assays, :samples, :studies, :publications, :events, :collections, only: [:index]
  end

  resources :presentations, concerns: [:has_content_blobs, :publishable, :has_versions, :asset] do
    resources :people, :projects, :publications, :events, :collections, only: [:index]
  end

  resources :models, concerns: [:has_content_blobs, :publishable, :has_doi, :has_versions, :asset] do
    member do
      get :compare_versions
      post :compare_versions
      get :visualise
      post :submit_to_sycamore
      post :export_as_xgmml
      post :execute
      get :simulate
      post :simulate
    end
    resources :model_images do
      collection do
        post :new
      end
      member do
        post :select
      end
    end
    resources :people, :projects, :investigations, :assays, :studies, :publications, :events, :collections, only: [:index]
  end

  resources :sops, concerns: [:has_content_blobs, :publishable, :has_doi, :has_versions, :asset] do
    resources :experimental_conditions do
      collection do
        post :create_from_existing
      end
    end
    resources :people, :projects, :investigations, :assays, :samples, :studies, :publications, :events, :workflows, :collections, only: [:index]
  end

  resources :workflows, concerns: [:has_content_blobs, :publishable, :has_doi, :has_versions, :asset] do
    collection do
      post :create_content_blob
      post :create_ro_crate
      get :provide_metadata
      post :metadata_extraction_ajax
      post :create_metadata
    end
    member do
      get :diagram
      get :ro_crate
    end
    resources :people, :projects, :investigations, :assays, :samples, :studies, :publications, :events, :sops, :collections, only: [:index]
  end

  resources :nodes, concerns: [:has_content_blobs, :publishable, :has_doi, :has_versions, :asset] do
    resources :people, :projects, :investigations, :assays, :samples, :studies, :publications, :events, :collections, only: [:index]
  end

  resources :content_blobs, except: [:show, :index, :update, :create, :destroy] do
    collection do
      post :examine_url
    end
  end
  resources :programmes do
    resources :avatars do
      member do
        post :select
      end
    end
    collection do
      post :items_for_result
      get :awaiting_activation
      get :administer_create_project_request
      post :respond_create_project_request
    end
    member do
      get :activation_review
      put :accept_activation
      put :reject_activation
      get :reject_activation_confirmation
      get :storage_report
    end
    resources :people, :projects, :institutions, :investigations, :studies, :assays,
              :data_files, :models, :sops, :workflows, :nodes, :presentations, :documents, :events, :publications, :organisms, :human_diseases, :collections, only: [:index]
  end

  resources :publications, concerns: [:asset] do
    collection do
      get :query_authors
      get :query_authors_typeahead
      get :export
      post :fetch_preview
      post :update_metadata
    end
    member do
      post :disassociate_authors
      post :update_metadata
      post :request_contact
    end
    resources :people, :projects, :investigations, :assays, :studies, :models, :data_files, :documents, :presentations, :organisms, :events, :collections, only: [:index]
  end

  resources :events, concerns: [:asset] do
    resources :people, :projects, :data_files, :publications, :documents, :presentations, :collections, only: [:index]
  end

  resource :policies do
    collection do
      post :preview_permissions
    end
  end

  resources :spreadsheet_annotations, only: [:create, :destroy, :update]

  resources :strains, concerns: [:asset] do
    collection do
      get :existing_strains_for_assay_organism
      get :strains_of_selected_organism
    end
    resources :specimens, :assays, :people, :projects, :samples, only: [:index]
  end

  resources :organisms do
    collection do
      post :search_ajax
    end
    resources :projects, :assays, :studies, :models, :strains, :specimens, :samples, :publications, only: [:index]
    member do
      get :visualise
    end
  end

  resources :human_diseases do
    collection do
      post :search_ajax
    end
    resources :projects, :assays, :studies, :models, :publications, only: [:index]
    member do
      get :visualise
      get :tree
    end
  end

  resources :tissue_and_cell_types
  resources :statistics do
    collection do
      get :application_status
    end
  end

  resources :site_announcements do
    collection do
      get :feed
      get :notification_settings
      post :update_notification_settings
    end
  end

  ### SAMPLES ###

  resources :samples, concerns: [:asset] do
    collection do
      get :attribute_form
      get :filter
    end
    resources :people, :projects, :assays, :studies, :investigations, :data_files, :publications, :samples,
              :strains, :organisms, :collections, only: [:index]
  end

  ### SAMPLE TYPES ###
  #
  resources :sample_types do
    collection do
      post :create_from_template
      get :select
      get :filter_for_select
    end
    member do
      get :template_details
      get :batch_upload
    end
    resources :samples
    resources :content_blobs do
      member do
        get :download
      end
    end
    resources :projects, only: [:index]
  end

  ### SAMPLE CONTROLLED VOCABS ###

  resources :sample_controlled_vocabs

  ### DOCUMENTS

  resources :documents, concerns: [:has_content_blobs, :publishable, :has_doi, :has_versions, :asset] do
    resources :people, :projects, :programmes, :investigations, :assays, :studies, :publications, :events, :collections, only: [:index]
  end

  resources :collections, concerns: [:publishable, :has_doi, :asset] do
    resources :items, controller: :collection_items
    resources :people, :projects, :programmes, :investigations, :assays, :studies, :publications, :events, :collections, only: [:index]
    resources :avatars do
      member do
        post :select
      end
    end
  end

  ### ASSAY AND TECHNOLOGY TYPES ###

  get '/assay_types/', to: 'assay_types#show', as: 'assay_types'
  get '/modelling_analysis_types/', to: 'assay_types#show', as: 'modelling_analysis_types'
  get '/technology_types/', to: 'technology_types#show', as: 'technology_types'

  ### MISC MATCHES ###
  get '/search/' => 'search#index', as: :search
  get '/search/save' => 'search#save', as: :save_search
  get '/search/delete' => 'search#delete', as: :delete_search
  post '/search/items_for_result' => 'search#items_for_result'
  get 'svg/:id.:format' => 'svg#show', as: :svg
  get '/tags/latest' => 'tags#latest', as: :latest_tags
  get '/tags/query' => 'tags#query', as: :query_tags
  get '/tags' => 'tags#index', as: :all_tags
  get '/tags/:id' => 'tags#show', as: :show_tag
  get '/tags' => 'tags#index', as: :all_anns
  get '/tags/:id' => 'tags#show', as: :show_ann
  get '/countries/:country_code' => 'countries#show', as: :country

  get '/data_fuse/' => 'data_fuse#show', as: :data_fuse
  post '/favourite_groups/new' => 'favourite_groups#new', as: :new_favourite_group
  post '/favourite_groups/create' => 'favourite_groups#create', as: :create_favourite_group
  post '/favourite_groups/edit' => 'favourite_groups#edit', as: :edit_favourite_group
  post '/favourite_groups/update' => 'favourite_groups#update', as: :update_favourite_group
  delete '/favourite_groups/:id' => 'favourite_groups#destroy', as: :delete_favourite_group
  post 'experiments/create_investigation' => 'studies#create_investigation', as: :create_investigation

  get '/signup' => 'users#new', as: :signup

  get '/logout' => 'sessions#destroy', as: :logout
  get '/login' => 'sessions#new', as: :login
  get '/create' => 'sessions#create', as: :create_session
  # Omniauth
  post '/auth/:provider' => 'sessions#create', as: :omniauth_authorize # For security, ONLY POST should be enabled on this route.
  match '/auth/:provider/callback' => 'sessions#create', as: :omniauth_callback, via: [:get, :post] # Callback routes need both GET and POST enabled.
  match '/identities/auth/:provider/callback' => 'sessions#create', via: [:get, :post] # Needed for legacy support..

  get '/activate(/:activation_code)' => 'users#activate', as: :activate
  get '/forgot_password' => 'users#forgot_password', as: :forgot_password
  get '/policies/request_settings' => 'policies#send_policy_data', as: :request_policy_settings
  get '/fail' => 'fail#index', as: :fail

  get '/whoami' => 'users#whoami'

  # feedback
  get '/home/feedback' => 'homes#feedback', as: :feedback

  # error rendering
  get '/404' => 'errors#error_404'
  get '/422' => 'errors#error_422'
  get '/500' => 'errors#error_500'
  get '/503' => 'errors#error_503'

  get '/zenodo_oauth_callback' => 'zenodo/oauth2/callbacks#callback'
  get '/seek_nels' => 'nels#callback', as: 'nels_oauth_callback'

  get '/citation/(*doi)' => 'citations#fetch', as: :citation, constraints: { doi: /.+/ }

app/helpers/spreadsheet_helper.rb
module SpreadsheetHelper
  include Seek::Data::SpreadsheetExplorerRepresentation

  def generate_paginate_rows(rows, sheet_index, per_page)
    # need to record the index of the nil row, for later use
    rows_with_index = []
    rows = rows.drop(1) if rows.first.nil?
    rows.each_with_index do |row, index|
      if row.nil?
        rows_with_index << Row.new(index + 1)
      else
        rows_with_index << row
      end
    end

    if sheet_index == params[:sheet].try(:to_i)
      current_page = params[:page].try(:to_i) || 1
    else
      current_page = 1
    end
    WillPaginate::Collection.create(current_page, per_page, rows_with_index.count) do |pager|
      start = (current_page - 1) * per_page # assuming current_page is 1 based.
      pager.replace(rows_with_index[start, per_page]) unless rows_with_index[start, per_page].nil?
    end
  end
end

app/views/spreadsheets/_annotation.html.erb
  <%  if (annotation.annotation_attribute.name == "plot_data") -%>
      <%= render :partial=>"spreadsheets/annotation_plot_data",:object=>annotation -%>
  <% else -%>
      <%= render :partial=>"spreadsheets/annotation_text_data",:object=>annotation -%>
  <% end -%>

app/views/spreadsheets/_annotation_form.html.erb
<div id="annotation_form" class="spreadsheet_popup" style="display:none">
  <div class="spreadsheet_box_title">
    <div style="float: left">New Annotation</div>
    <div style="float: right"><a href="#" onclick="$j('#annotation_form').hide(); return false;">Close</a></div>
    <br style="clear:both"/>
  </div>
  <%= form_tag(spreadsheet_annotations_path, method: :post, class: 'spreadsheet-annotation-ctrl',
               id: "new_annotation_form", remote: true) do  %>
    <%= hidden_field_tag :annotation_content_blob_id, @display_data_file.content_blob.id %>
    <%= hidden_field_tag :annotation_sheet_id, "0" %>
    
    <p>
      Cell Range:<br/>
      <%= text_field_tag :annotation_cell_coverage, nil,:class=>"annotation_cell_coverage_class" %>
    </p>

    <p>
      Content:<br/>
      <%= text_area_tag :annotation_content,nil %>
      <%= hidden_field_tag :annotation_attribute_name, "annotation" %>
    </p>
                       
    <%= submit_tag 'Add Annotation',:id=>"create_annotation_button" %>
  <% end %>
  <%= image_tag "ajax-loader.gif", :id => 'spinner', :style => 'display:none;', :class => 'loading-spinner' -%>
</div>

app/views/spreadsheets/_annotation_javascript.html.erb
<script type="text/javascript">
var annotation_sources = [];
var as;

<% annotations.reverse.group_by(&:source).each do |source, annotation_subset| -%>
  as = new annotation_source(<%= source.id -%>, '<%= source.class.name -%>', '<%= source.person.name -%>', '<%= polymorphic_path(source.person) -%>');
  annotation_sources.push(as);
  <% annotation_subset.each do |a| -%>
    as.annotations.push(new annotation(<%= a.id -%>, '<%= a.annotation_attribute.name -%>', <%= a.annotatable.worksheet.sheet_number -%>, '<%= a.annotatable.cell_range -%>', '<%= h escape_javascript a.value.text -%>', '<%= time_ago_in_words(a.created_at) -%> ago'));
  <% end -%>
<% end -%>

$j(document).ready(function () {
  var oldAnnotatedCells = $j("td.annotated_cell").removeClass("annotated_cell");

  bindAnnotations(annotation_sources);

  //Flash the annotations that were added/deleted
  var newAnnotatedCells = $j("td.annotated_cell");
  if(newAnnotatedCells != oldAnnotatedCells) {
    oldAnnotatedCells.not(newAnnotatedCells).unbind("click").effect("highlight", {color: "#FF0000"}, 600);
    newAnnotatedCells.not(oldAnnotatedCells).effect("highlight", {color: "#00FF00"}, 600);
  }
});

</script>

app/views/spreadsheets/_annotation_plot_data.html.erb
<% annotation = annotation_plot_data -%>
<div class="annotation annotation_plot_data" id="annotation_<%=annotation.id-%>">
  <%= form_tag(spreadsheet_annotation_path(annotation), method: :put, class: 'spreadsheet-annotation-ctrl',
               id: "edit_plot_data_form_#{annotation.id}", remote: true) do  %>
      <div class="annotation_content">
        <div class="annotation_avatar">
          <%= avatar(annotation.source.person, 24) -%>
        </div>
        <div class="annotation_text">
          <%= link_to(annotation.source.person.name, annotation.source.person)%><br/>
        </div>

        <div id="annotation_plot_data_<%= annotation.id -%>">

        </div>
        <div>&nbsp;</div>
        <br style="clear:both"/>

      </div>
      <div class="annotation_footer">
        <div style="float:left"><%= time_ago_in_words(annotation.created_at) %> ago</div>
        <div style="float:right">
          <% if annotation.source == current_user %>
            <%= link_to image('spreadsheet_annotation_destroy', :title => "Delete Annotation"),
                        spreadsheet_annotation_path(annotation), remote: true, method: :delete,
                        class: 'spreadsheet-annotation-ctrl' -%>
            <%= image_tag "ajax-loader.gif", :id => "spinner"+annotation.id.to_s, :class => 'loading-spinner', :style => 'display:none;' -%>
          <% end -%>
          <span class="cell_coverage"><a href="#" onclick="select_range(this.innerHTML);return false;"><%= annotation.annotatable.cell_range -%></a></span>
        </div>
        <br style="clear:both"/>
        <div id="annotation_controls" style="display:none">
          <%= submit_tag 'Save Changes',:id=>"edit_plot_data_button" %> or <%= cancel_button("", :onclick => "toggle_annotation_form('" + annotation.id.to_s + "'); return false;") %>
        </div>
      </div>
      <% end %>
</div>

app/views/spreadsheets/_annotation_text_data.html.erb
<% annotation = annotation_text_data %>
<div class="annotation" id="annotation_<%= annotation.id -%>">
  <%= form_tag(spreadsheet_annotation_path(annotation), method: :put, class: 'spreadsheet-annotation-ctrl',
               id: "edit_annotation_form_#{annotation.id}", remote: true) do %>
      <div class="annotation_content">
        <div class="annotation_avatar">
          <%= avatar(annotation.source.person, 24) -%>
        </div>
        <div class="annotation_text">
          <%= link_to(annotation.source.person.name, annotation.source.person) %>
          <br/>
          <%= h annotation.value_content %>
          <br/>
        </div>
        <div class="annotation_edit_text" style="display:none;">
          <%= link_to(annotation.source.person.name, annotation.source.person) %>
          <br/>
          <%= text_area_tag :annotation_content, annotation.value_content %>
        </div>
        <br style="clear:both"/>
      </div>
      <div class="annotation_footer">
        <div style="float:left"><%= time_ago_in_words(annotation.created_at) %> ago</div>
        <div style="float:right">
          <% if annotation.source == current_user %>
            <%= link_to image('spreadsheet_annotation_destroy', :title => "Delete Annotation"),
                        spreadsheet_annotation_path(annotation), remote: true, method: :delete,
                        class: 'spreadsheet-annotation-ctrl' -%>
            <%= link_to(image('spreadsheet_annotation_edit', :title => "Edit Annotation"), '#', :onclick => "toggle_annotation_form('" + annotation.id.to_s + "'); return false;") -%>
            <%= image 'spinner', :id => "spinner"+annotation.id.to_s, :class => 'loading-spinner', :style => 'display:none;' -%>
          <% end -%>
          <span class="cell_coverage"><a href="#" onclick="select_range(this.innerHTML);return false;"><%= annotation.annotatable.cell_range -%></a></span>
        </div>
        <br style="clear:both"/>

        <div id="annotation_controls" style="display:none">
          <%= submit_tag 'Save Changes', :id => "edit_annotation_button_#{annotation.id}", class: 'btn btn-primary' %>
          or <%= cancel_button("", :onclick => "toggle_annotation_form('" + annotation.id.to_s + "'); return false;") %>
        </div>
      </div>
  <% end %>
</div>

app/views/spreadsheets/_annotations.html.erb
<div id="annotation_container" style="display:none">
  <div id="annotation_drag"><a href="#" onclick="$j('#annotation_container').hide();">Close</a></div>
  <%= render :partial => "spreadsheets/annotation", :collection => annotations %>
</div>
<div id="annotation_overview" class="spreadsheet_popup" style="display:none">
  <div class="spreadsheet_box_title">
    <div style="float: left">Listing Annotations</div>
    <div style="float: right"><a href="#" onclick="$j('#annotation_overview').hide(); return false;">Close</a></div>
    <br style="clear:both"/>
  </div>
  <table>
    <colgroup><col/><col/><col/></colgroup>
  </table>
</div>

<%= render :partial => "spreadsheets/annotation_javascript", :locals => {:annotations => annotations} %>

app/views/spreadsheets/_export.html.erb
<div id="export_form" class="spreadsheet_popup" style="display:none">
  <div class="spreadsheet_box_title">
    <div style="float: left">Export Selection</div>
    <div style="float: right"><a href="#" onclick="$j('#export_form').hide(); return false;">Close</a></div>
    <br style="clear:both"/>
  </div>
  <p>
    The data in the text box below can be copied and pasted into Microsoft Excel.<br/>
    Make sure when pasting the data, "tabs" are selected as the column delimiter.
  </p>

  <br/>

  <textarea style="width: 25em; height: 20em" id="export_data"></textarea>
</div>

app/views/spreadsheets/_matched_lines.erb
<% unless sheet_array.blank? %>
    <div class="list_item with_smaller_shadow curved">
      <%= list_item_title object %>
      <div id="item_<%= object.id %>">
        <%= render :partial => "spreadsheets/row", :locals => {:sheet_array => sheet_array, :object_id => object.id} %>
        <%= link_to_function ("View more details " + expand_image).html_safe, :style => "background_display: block;", :id => 'show_details_image_' + object.id.to_s do |page|
          page << "if (!document.getElementById('item_#{object.id}_details')) {"
          page.insert_html :after, "item_" + object.id.to_s, "<div id='item_#{object.id}_details' style='display: block;'></div>"
          page.replace_html 'item_'+ object.id.to_s + "_details", :partial => "assets/resource_list_item", :locals => {:resource_list_item => object}
          page << "}"
          page << "else {"
          page.visual_effect :toggle_blind, "item_#{object.id}_details", :duration => 0.5
          page << "}"

          page["show_details_image_#{object.id}"].toggle
          page["hide_details_image_#{object.id}"].toggle
        end
        -%>
        <%= link_to_function ("View more details " + collapse_image).html_safe, :style => "display: none;", :id => 'hide_details_image_' + object.id.to_s do |page|
          page.visual_effect :toggle_blind, "item_#{object.id}_details", :duration => 0.5
          page["show_details_image_#{object.id}"].toggle
          page["hide_details_image_#{object.id}"].toggle
        end
        -%>
      </div>
    </div>
<% end %>

app/views/spreadsheets/_plot.html.erb
<div id="plot_panel" class="spreadsheet_popup" style="display:none">
  <div class="spreadsheet_box_title">
    <div style="float: left">Data plot</div>
    <div style="float: right"><a href="#" onclick="$j('#plot_panel').hide(); return false;">Close</a></div>
    <br style="clear:both"/>
  </div>
  

  <div id="plot_data">

  </div>
  <div>&nbsp;</div>
  <%= form_tag(spreadsheet_annotations_path, method: :post, class: 'spreadsheet-annotation-ctrl',
               id: "plot_panel_form", remote: true) do  %>
    <div style="display:none;">
      <%= hidden_field_tag :annotation_content_blob_id, @display_data_file.content_blob.id %>
      <%= hidden_field_tag :annotation_sheet_id, "0" %>

      <%= text_field_tag :annotation_cell_coverage, nil,:class=>"annotation_cell_coverage_class" %>

      <%= text_area_tag :annotation_content,nil,:class=>"annotation_content_class" %>
      <%= hidden_field_tag :annotation_attribute_name, "plot_data" %>
    </div>
    <%= submit_tag('Store as annotation',:id=>"store_plot_button") if logged_in? %>
  <% end %>
  <%= image_tag "ajax-loader.gif", :id => 'spinner_plot', :style => 'display:none;', :class => 'loading-spinner' -%>

</div>

app/views/spreadsheets/_spreadsheet.html.erb
<%
   default_per_page = 200
   if workbook.sheets.count > 3
     default_per_page = 100
   end
%>
<% per_page = params[:page_rows].try(:to_i) || default_per_page %>

<div class="spreadsheet_container" onselectstart="return false;">
<% workbook.sheets.each_with_index do |sheet, sheet_index| -%>
    <% unless sheet.rows.empty? %>
        <a index="<%= sheet_index + 1 -%>" class="sheet_tab curved_top with_smaller_shadow <%= "selected_tab" if workbook.sheets.first == sheet -%>"><%= h(sheet.name) -%></a>
    <% end %>
<% end %>
  <!--- Sheets --->
  <% workbook.sheets.each_with_index do |sheet,index| -%>
      <% sheet_index = index + 1 %>
      <% unless sheet.rows.empty? %>
          <%
             wp_rows = generate_paginate_rows(sheet.rows, sheet_index, per_page)
          %>
          <div style="display:none" class="sheet_container curved" id="<%= ("spreadsheet_" + sheet_index.to_s) -%>">
            <div class="corner_heading">&nbsp;</div>
            <div class="col_headings <%= "odd_heading" if sheet.last_col % 2 == 0 -%>">
              <div style="min-width:1000000px">
                <div class="col_heading_spacer">&nbsp;</div>
                <% sheet.columns.each_with_index do |col,c| -%>
                    <div style="<%= (("width:" + (col.width.to_f/31).to_i.to_s) + "px") unless col.width.nil? -%>" class="col_heading <%= "odd_heading" if c % 2 == 0  -%>"><%= to_alpha(col.index) -%></div>
                <% end -%>
                <br style=" clear:both"/>
              </div>
            </div>

            <div>
              <div class="row_headings <%= "odd_heading" if sheet.last_row % 2 == 0 -%>" style="float:left">
                <% wp_rows.each do |row| -%>
                    <% r = row.index  %>
                    <div <%= (sheet[r].nil? || sheet[r].height.nil?) ? "" : "style =\"height:"+sheet[r].height+"\"" -%> class="row_heading <%= "odd_heading" if r % 2 == 1 -%>"><%= r -%></div>
                <% end -%>
                <div style="height: 20px">&nbsp;</div>
              </div>
              <div class="sheet" id="<%= ("spreadsheet_" + sheet_index.to_s) -%>">
                <table class="sheet" cellspacing="0" cellpadding="0">
                  <!--- Columns --->
                  <colgroup>
                    <% sheet.columns.each do |col| -%>
                        <col style="<%= (("width:" + (col.width.to_f/31).to_i.to_s) + "px") unless col.width.nil?  -%>">
                    <% end -%>
                  </colgroup>

                  <!--- Rows --->
                  <% wp_rows.each do |row| -%>
                      <% r = row.index  %>
                      <% height =(sheet[r].nil? || sheet[r].height.nil?) ? "" : "style =\"height:"+sheet[r].height+"\"" -%>
                      <tr <%= height -%>>
                        <!--- Cells --->
                        <% 1.upto(sheet.last_col) do |c| %>
                            <% if sheet[r] && sheet[r][c] -%>
                                <% cell = sheet[r][c] -%>
                                <td row="<%= r -%>" col="<%= c -%>" id="cell_<%= to_alpha(c) + r.to_s -%>" title="<%= ("=" + cell.formula unless cell.formula.nil?) || "" -%>" class="cell <%= cell.style || ""-%>"><%= auto_link(h(cell.value),:html=>{:target=>"_blank"}) -%></td>
                            <% else -%>
                                <td row="<%= r -%>" col="<%= c -%>" id="cell_<%= to_alpha(c) + r.to_s -%>" class="cell"></td>
                            <% end -%>
                        <% end -%>
                      </tr>
                  <% end -%>

                </table>
              </div>
              <br style="clear:both"/>
            </div>
          </div>

          <%= will_paginate(wp_rows,
                            :id => "paginate_sheet_#{sheet_index.to_s}",
                            :params => {:sheet => sheet_index, :page_rows => per_page, :annotation_id => nil},
                            :previous_label => "&#8593; Previous",
                            :next_label => "Next &#8595;") %>

      <% end -%>
  <% end -%>
</div>
<br/>

<div id="rows_per_page" style="display:none">
  Display <%= text_field_tag :per_page, per_page, :size => 4, :onkeypress => 'return onlyNumbers(event);' %> rows per page
  <input type='button' value='Update' onclick='changeRowsPerPage()'/>
</div>

<script type = "text/javascript">
    var perPage = <%= default_per_page %>;

    <% if params[:page_rows] %>
    perPage = <%= params[:page_rows].try(:to_i) %>;
    <% end %>

    window.onload=function(){
        //"activate" the worksheet
        activateSheet(<%= params[:sheet].try(:to_i) || 1 %>);
        displayAnnotation();
        displayRowsPerPage();
    };

    function displayAnnotation(){
        <% a = Annotation.find_by_id(params[:annotation_id]) %>
        <% if a %>
        var ann = new annotation(<%= a.id -%>, '<%= a.annotation_attribute.name -%>', <%= a.annotatable.worksheet.sheet_number -%>, '<%= a.annotatable.cell_range -%>', '<%= h escape_javascript a.value.text -%>', '<%= time_ago_in_words(a.created_at) -%> ago');
        jumpToAnnotation(ann.id, ann.sheetNumber+1, ann.cellRange);
        <% end %>
    }
</script>
      

app/views/spreadsheets/_spreadsheet_errors.html.erb
<div class="spreadsheet_errors">
  <h1><%= errors.size > 1 ? "Errors" : "An error"-%> occurred whilst <%= verb -%> your annotation</h1>
  <ul>
    <% errors.each do |attribute, errors_array| %>
      <li><%= errors_array.html_safe %></li>
    <% end %>
  </ul>
</div>

app/views/spreadsheets/_spreadsheet_styles.html.erb
<style type="text/css" id="generated_spreadsheet_styles">
  <% styles.each_key do |style_name| -%>
    td.<%= style_name -%> {
    <% styles[style_name].attributes.each_key do |a| -%>
      <%#Borders are removed here because they break the table layout in chrome and possibly IE-%>
      <%= a + ": " + styles[style_name][a] + ";" unless a.include?("border")%>
    <% end %>
    }
  <% end %>
</style>
  